CI Baxter Traffic Sim: ResourceManager Class Reference
ResourceManager Class Reference
ResourceManager is a class that is attached to a GameObject to control and keep track of different simulation elements.
Public Member Functions
void Start ()
Start() is called before the first frame, Start() initalizes the global variables, calls ShowResources(), and PauseSim().
void Update ()
Every frame Update() checks if the p key was pressed and calls PauseSim() or ResumeSim() depending on the ready up flag. Also it updates the time variables, and calls ShowResources().
void IncrementTime ()
void resetAdjust ()
void PauseSim ()
Sets the global time scale to 0 to pause the simulation.
void ResumeSim ()
Sets the global time scale to 1 to resume the simulation.
void ShowResources ()
Updates the UI text.
void AdjustPedLimit (float newLimit)
void AdjustAmbientLimit (float newLimit)
Public Attributes
Text timeText
Text carCountText
Text pedCountText
int carCount
int pedCount
int pedsSpawned = 0
int carCountA
int pedLimit = 250
int ambientLimit = 25
Static Public Attributes
static float seconds
static float minutes
static bool readyUp = false
static bool initialAdjust = false
Detailed Description
ResourceManager is a class that is attached to a GameObject to control and keep track of different simulation elements.
Member Function Documentation
AdjustAmbientLimit()
void ResourceManager.AdjustAmbientLimit (float newLimit)
References ambientLimit.
AdjustPedLimit()
void ResourceManager.AdjustPedLimit (float newLimit)
References pedLimit.
IncrementTime()
void ResourceManager.IncrementTime ()
References initialAdjust, minutes, readyUp, and seconds.
Referenced by Update().
PauseSim()
void ResourceManager.PauseSim ()
Sets the global time scale to 0 to pause the simulation.
Referenced by Start(), and Update().
resetAdjust()
void ResourceManager.resetAdjust ()
References initialAdjust, and readyUp.
ResumeSim()
void ResourceManager.ResumeSim ()
Sets the global time scale to 1 to resume the simulation.
Referenced by Update().
ShowResources()
void ResourceManager.ShowResources ()
Updates the UI text.
References carCount, minutes, pedCount, and seconds.
Referenced by Start(), and Update().
Start()
void ResourceManager.Start ()
Start() is called before the first frame, Start() initalizes the global variables, calls ShowResources(), and PauseSim().
References minutes, PauseSim(), readyUp, seconds, and ShowResources().
Update()
void ResourceManager.Update ()
Every frame Update() checks if the p key was pressed and calls PauseSim() or ResumeSim() depending on the ready up flag. Also it updates the time variables, and calls ShowResources().
References IncrementTime(), PauseSim(), pedCount, readyUp, ResumeSim(), and ShowResources().
Member Data Documentation
ambientLimit
int ResourceManager.ambientLimit = 25
Referenced by AdjustAmbientLimit().
carCount
int ResourceManager.carCount
Stores the car count
Referenced by ShowResources().
carCountA
int ResourceManager.carCountA
carCountText
Text ResourceManager.carCountText
stores a text UI object for the car count.
initialAdjust
bool ResourceManager.initialAdjust = false static
Referenced by IncrementTime(), and resetAdjust().
minutes
float ResourceManager.minutes static
Stores the Minutes
Referenced by IncrementTime(), ShowResources(), and Start().
pedCount
int ResourceManager.pedCount
Stores the pedestrian count
Referenced by ShowResources(), and Update().
pedCountText
Text ResourceManager.pedCountText
stores a text UI object for the pedestrian count.
pedLimit
int ResourceManager.pedLimit = 250
Referenced by AdjustPedLimit().
pedsSpawned
int ResourceManager.pedsSpawned = 0
readyUp
bool ResourceManager.readyUp = false static
acts as a flag for pausing and unpausing.
Referenced by IncrementTime(), resetAdjust(), Start(), and Update().
seconds
float ResourceManager.seconds static
Stores the seconds
Referenced by IncrementTime(), ShowResources(), and Start().
timeText
Text ResourceManager.timeText
stores a text UI object for the time.
The documentation for this class was generated from the following file:
C:/Users/Dylan Stewart/Documents/GitHub/Project-Baxter-Sim---Team-Matrix/Matrix_CI_TrafficFlow/Assets/Scripts/Resource Handler/ResourceManager.cs